In [3]:
import numpy as np

In [13]:
x = np.random.randint(1,9,(4,3))
y = np.random.randint(1,7,(4,3))

In [14]:
z = x + y

In [15]:
x,y,z

(array([[7, 7, 8],
        [3, 5, 5],
        [5, 6, 7],
        [8, 4, 2]]),
 array([[6, 6, 2],
        [3, 2, 5],
        [1, 2, 5],
        [3, 2, 1]]),
 array([[13, 13, 10],
        [ 6,  7, 10],
        [ 6,  8, 12],
        [11,  6,  3]]))

In [23]:
a = np.array([[2,5,3,78],[56,4,8,9]])
b = np.array([[23,44,54,6],[21,6,78,45]])
c = a * b
c

array([[  46,  220,  162,  468],
       [1176,   24,  624,  405]])

In [18]:
a1 = np.random.randint(3,10,(2,2))
result = np.empty((2,2))
a1

array([[5, 6],
       [7, 4]])

In [21]:
len(a1[0])

2

In [20]:
for i in range(len(a1)):
   # iterate through columns
   for j in range(len(a1[0])):
        result[j][i] = a1[i][j]
for r in result:
    print(r)

[5. 7.]
[6. 4.]


In [4]:
str = input("enter string: ")
words = str.split()
words.sort()
for word in words:
    print(word)


enter string: Your Broadband Gateway
Broadband
Gateway
Your


In [5]:
punctuation =  '''!()–[]-'{}:;,`~‘“,<>./?@#$%^&*_'''
str1 = input("Enter the string: ")
no_punctuation = ""
for char in str1:
    if char not in punctuation:
        no_punctuation = no_punctuation + char
print(no_punctuation)

Enter the string: i$ne@#u!r)on; T)opi!cs.: P}yth-on {Beg~inn;ers T-ut,o.r'ial
ineuron Topics Python Beginners Tutorial
